
[build]
  command = "npm run build"  # Change this if necessary
  publish = "out"  # Ensure this is the correct output folder

[dev]
  command = "npm start"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
